# Generated by Django 4.1.1 on 2023-10-23 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_mimicnumber_mimic_number'),
        ('reports', '0006_forcedoutagereport_hold_date_time_retored_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedOutage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cause', models.CharField(max_length=1000, null=True)),
                ('remarks', models.CharField(max_length=1000, null=True)),
                ('installed_capacity', models.PositiveIntegerField(null=True)),
                ('number_of_tx', models.PositiveIntegerField(null=True)),
                ('affected_areas', models.CharField(max_length=1000, null=True)),
                ('outage_description', models.CharField(max_length=1000, null=True)),
                ('planned_date_time_out', models.CharField(max_length=1000, null=True)),
                ('planned_date_time_restored', models.CharField(max_length=1000, null=True)),
                ('actual_date_time_out', models.CharField(max_length=1000, null=True)),
                ('actual_date_time_restored', models.CharField(max_length=1000, null=True)),
                ('load', models.PositiveIntegerField(null=True)),
                ('feeder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.feeder')),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planned_outage_records', to='reports.basereport')),
            ],
        ),
    ]
